.TH MQTT_INSPECTOR 1 "February 2026" "mqtt-inspector 0.1.0"
.SH NAME
mqtt-inspector \- MQTT message inspector for IoT
.SH SYNOPSIS
.B mqtt-inspector
.SH DESCRIPTION
.B mqtt-inspector
is a GTK4 application for LMQTT message inspector for IoT.
.SH OPTIONS
None currently supported.
.SH AUTHOR
Daniel Nylander <daniel@danielnylander.se>
.SH SEE ALSO
.BR gtk4 (7)
